### ISSUE TITLE
Errors while installation

### ISSUE THREAD

**Issue by jupakajo** [sanealytics/recommenderlabrats#1]
Hi...

the package looks really, really interesting.
I tried to install it the way you described on several machines. However, I cannot get it to work.
Maybe it is just me, maybe it is a general problem. I would be happy about a note or comment. I created two gists, one for the Windows installation log and the other one is on SUSE Enterprise Server Linux.
For Linux:
https://gist.github.com/1f2ef7257e09eea9df3b.git

For Windows:
https://gist.github.com/29becf24a8e2d91aec11.git

Thanks for your help and comments.

Ferb

**Comment by sanealytics** [comment]
Hi Ferbster,

Thank you for trying this package. I cannot see your gists for some reason. My guess is the dependencies I have on openMP. I will try to make them optional. Currently it requires you to have OpenMP BLAS installed.

I will update this issue when that is no longer a requirement.

**Comment by rama-rajkumar** [comment]
@sanealytics 
Thank you for the package, but I am facing the same issue while installing it on a Linux machine as commented by @Ferbster. Any further updates?

**Comment by sanealytics** [comment]
I don't imagine you are still interested in this issue, but I finally got to spend some time on it. It should be fixed now. Please let me know if you still see issues.
