### ISSUE TITLE
What is the status of this?

### ISSUE THREAD

**Issue by vspinu** [sanealytics/recommenderlabrats#2]
Thanks for providing this. Would be great to see more docs. What are the use cases for ALS and IMPLICIT recommender systems?

**Comment by sanealytics** [comment]
When possible, it is fastest to do batch RSVD. However it is memory intensive. In practice we end up solving User matrix first fixing the random Item matrix. Then fix the somewhat better User matrix and solve for a new Item matrix and so on.. this is ALS and is what facebook, netflix, etc use. Here is a simple version of it.

In most problems, we don't get actual ratings, so we use imputed weights. This is what IMPLICIT does. This was one of the main algorithms for Spotify back in the day and is also what I used earlier in Rent The Runway. Read this paper - http://yifanhu.net/PUB/cf.pdf

We can now use factorization machines, RBMs, RNNs, etc but I have been developing those in other languages and haven't had time to port them here. 

I welcome pull requests of course :)
