### ISSUE TITLE
Provide more information regarding OpenMP in Readme

### ISSUE THREAD

**Issue by benjaminvdb** [sanealytics/recommenderlabrats#3]
It took me quite some time to figure out how to enable compilation with OpenMP on my systems (Mac OS X 10.11.6 and Ubuntu 14.04.4 LTS). A few pointers might prove helpful for some users. For example, I could just copy the Makevars file to ~/.R/ but I wasn't aware of this.

I'll submit a pull request to make a start.

**Comment by saurabhRTR** [comment]
Thank you for that. I will merge this.
